theme: jekyll-theme-minimal
title: Vladislav Kachenya
logo: MyPhotoCompressed.jpg
description: <p>Email&#58 <a href="mailto&#58v.s.kachenya@gmail.com">v.s.kachenya@gmail.com</a></p><p>Phone number&#58 \n<a a href="tel&#58+375298369188">+375 298369188</a></p><p>Location&#58 <a href="https&#58//yandex.by/maps/157/minsk/?ll=27.727359%2C53.882845&mode=search&sll=27.561481%2C53.902496&sspn=0.410614%2C0.159561&text=%D0%9C%D0%B8%D0%BD%D1%81%D0%BA&z=11">Minsk (Belarus)</a></p><p>Date of birth&#58 05/08/1995</p>
